# Generated by Django 5.1.7 on 2025-04-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_master_viev_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='viev_count',
            new_name='view_count',
        ),
    ]
